export const PERSONAL_INFO = {
  name: 'Aditya Kesharwani',
  role: 'Full Stack Developer',
  subtitle: 'Digital Architect & Backend Specialist',
  experienceYears: '5+',
  location: 'Jabalpur, Madhya Pradesh, India',
  timezone: 'IST (UTC+05:30)',
  rateRange: '$12–$25/hr',
  rateDetail: '$12.00 – $25.00 / HR USD',
  availability: 'Available for freelance & contract',
  status: 'SYS_ACTIVE // PRODUCTION READY',
  email: 'akesharwani.info@gmail.com',
  phone: '+919203530069',
  phoneFormatted: '+91 9203530069',
  website: 'https://adityakesharwani.com',
  websiteDisplay: 'adityakesharwani.com',
  linkedin: 'https://www.linkedin.com/in/aditya-kesharwani-1329531a0',
  linkedinDisplay: 'aditya-kesharwani-1329531a0',
  github: 'https://github.com/AdityaKesharwani',
  githubDisplay: 'AdityaKesharwani',
  specVersion: 'FULL-STACK V5.4',
  releaseYear: '2026',
};

export const TELEMETRY_METRICS = [
  {
    id: 'exp',
    counter: '5+',
    value: '5+',
    unit: 'YRS',
    title: 'Years Experience',
    label: 'Years Experience',
    description: 'Continuous enterprise engineering, product scaling, and software lifecycle oversight.',
    desc: 'Continuous enterprise engineering, product scaling, and software lifecycle oversight.',
  },
  {
    id: 'api',
    counter: '16+',
    value: '16+',
    unit: 'APIs',
    title: 'Job Portal Integrations',
    label: 'Job Portal Integrations',
    description: 'Automated bidirectional synchronization with major global recruiting exchanges.',
    desc: 'Automated bidirectional synchronization with major global recruiting exchanges.',
  },
  {
    id: 'diff',
    counter: '30%',
    value: '30%',
    unit: 'DIFF',
    title: 'Production Issue Reduction',
    label: 'Production Issue Reduction',
    description: 'Achieved via strict type enforcement, clean architecture, and automated test pipelines.',
    desc: 'Achieved via strict type enforcement, clean architecture, and automated test pipelines.',
  },
  {
    id: 'perf',
    counter: '25–30%',
    value: '25–30%',
    unit: 'OPT',
    title: 'Performance Improvement',
    label: 'Performance Improvement',
    description: 'Average database query latency reduction and front-end bundle load optimization.',
    desc: 'Average database query latency reduction and front-end bundle load optimization.',
  },
];
